version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network 

  app:
    build: .
    ports:
      - "8080:8080"
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./config:/app/config
    environment:
      POSTGRES_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable
      SERVER_PORT: ${SERVER_PORT}
      CONFIG_PATH: ${CONFIG_PATH}
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090" 
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: