{
 "title": "Avito PVZ - Buisiness Metrics",
 "panels": [
  {
   "title": "Points Created",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 3 },
   "targets": [
    { "expr": "sum(points_created_total)" }
   ]
  },
  {
   "title": "Points Errors",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 3 },
   "targets": [
    { "expr": "sum(points_created_errors)" }
   ]
  },
  {
   "title": "Products Created",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 3 },
   "targets": [
    { "expr": "sum(products_created_total)" }
   ]
  },
  {
   "title": "Products Errors",
   "type": "stat",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 3 },
   "targets": [
    { "expr": "sum(products_created_errors)" }
   ]
  },
  {
   "title": "Receptions Created",
   "type": "stat",
   "gridPos": { "x": 0, "y": 3, "w": 6, "h": 3 },
   "targets": [
    { "expr": "sum(reception_created_total)" }
   ]
  },
  {
   "title": "Receptions Errors",
   "type": "stat",
   "gridPos": { "x": 6, "y": 3, "w": 6, "h": 3 },
   "targets": [
    { "expr": "sum(reception_created_errors)" }
   ]
  }
 ]
}